=== aichaait/class-generator-1/Interfaces/MyLibraries/Convertion/project/DiagrammeDesClasses/DG.dtd
<!ELEMENT classes (class+)>
    <!ELEMENT class (attributes, methodes,associations)>
    <!ATTLIST class name ID #REQUIRED superClass IDREFS #IMPLIED>
        <!ELEMENT attributes (attribute*)>
            <!ELEMENT attribute EMPTY>
            <!ATTLIST attribute name CDATA #REQUIRED value CDATA #IMPLIED type CDATA #REQUIRED>
        <!ELEMENT methodes (methode*)>
            <!ELEMENT methode (parametres)>
            <!ATTLIST methode name CDATA #REQUIRED return CDATA #REQUIRED>
        <!ELEMENT parametres (parametre*)>
            <!ELEMENT parametre EMPTY>
            <!ATTLIST parametre name CDATA #REQUIRED type CDATA #REQUIRED>
        <!ELEMENT associations (association*)>
            <!ELEMENT association EMPTY>
            <!ATTLIST association type (simple | aggregation | composition) #REQUIRED classArrivee IDREF #REQUIRED role CDATA #REQUIRED multiplicity CDATA #REQUIRED>

=== aichaait/class-generator-1/Interfaces/MyLibraries/Convertion/project/DiagrammeDesClasses/DG.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE classes SYSTEM "DG.dtd">
<classes>
  <class name="A">
    <attributes>
      <attribute name="a" type="int" value="" />
    </attributes>
    <methodes>
      <methode name="ma" return="String">
        <parametres>
          <parametre name="e" type="int" />
        </parametres>
      </methode>
      <methode name="ma2" return="void">
        <parametres />
      </methode>
    </methodes>
    <associations />
  </class>
  <class name="B" superClass="A">
    <attributes>
      <attribute name="b" type="char" value="" />
    </attributes>
    <methodes />
    <associations>
      <association type="composition" classArrivee="C" multiplicity="*" role="lesC" />
    </associations>
  </class>
  <class name="C">
    <attributes>
      <attribute name="c" type="boolean" value="" />
    </attributes>
    <methodes />
    <associations />
  </class>
  <class name="F">
    <attributes />
    <methodes />
    <associations />
  </class>
</classes>
